apiVersion: v1
kind: PersistentVolume
metadata:
  name: wfw-kafka-2
spec:
  capacity:
    storage: 1Gi 
  accessModes: 
    - ReadWriteOnce
  glusterfs: 
    endpoints: glusterfs-cluster 
    path: wfw-zk
    readOnly: false
  persistentVolumeReclaimPolicy: Recycle
